### ISSUE TITLE
Fix README/plugin description

### ISSUE THREAD

**Issue by YannCebron** [Osiris-Team/Desku-Intellij-Plugin#1]
it misses closing `<!-- Plugin description -->` after _Features_ section

**Comment by Osiris-Team** [comment]
no? https://github.com/Osiris-Team/Desku-Intellij-Plugin/blob/271bebc1b6cf6504b9a94c52d255bd084ec2fbf5/README.md?plain=1#L29

I included the installation steps is that an issue?

**Comment by YannCebron** [comment]
Oh I see. They must not be part of the plugin description, they're shown in the IDE plugin manager and on the JetBrains Marketplace website.

**Comment by Osiris-Team** [comment]
@YannCebron Fixed
